allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  core-js-pure: true
  nx: true
  sharp: true
  unrs-resolver: true
  esbuild: false
  msgpackr-extract: true
  workerd: true
  '@prisma/engines': true
  prisma: true
  '@prisma/client': true
  bcrypt: true
  puppeteer: set this to true or false
