import { Request, Response } from 'express';
import { z } from 'zod';
import { prisma } from '../../lib/prisma';
import { GoogleGenAI, Type } from '@google/genai';
import { CurateSetlistSchema } from '@choir-workspace/shared-validation';

// Initialize the GenAI client
// It automatically picks up GEMINI_API_KEY from process.env
const ai = new GoogleGenAI();

class AiController {
  async curateSetlist(req: Request, res: Response) {
    try {
      const data = CurateSetlistSchema.parse(req.body);
      
      // Fetch catalog
      const songs = await prisma.song.findMany({
        
        select: {
          id: true,
          title: true,
          tempoBpm: true,
          originalKey: true,
          tags: true
        }
      });

      if (songs.length === 0) {
        return res.status(400).json({ error: 'No songs in the catalog to curate from.' });
      }

      const prompt = `
You are an expert Choir Director and Worship Leader. Your task is to curate a cohesive setlist based on the provided parameters and the choir's current repertoire.
If the catalog is small, you can also suggest 1 or 2 external songs that fit the theme well, leaving the 'songId' null for those.

Theme/Vibe requested: "${data.theme}"
Service Type: ${data.serviceType || 'Regular Sunday'}
Target number of songs: ${data.targetCount}

Available Repertoire (JSON):
${JSON.stringify(songs, null, 2)}
      `;

      const responseSchema = {
        type: Type.OBJECT,
        properties: {
          setlistTitle: { type: Type.STRING, description: 'A creative title for this setlist' },
          explanation: { type: Type.STRING, description: 'Brief explanation of why these songs were chosen and how they flow together.' },
          songs: {
            type: Type.ARRAY,
            items: {
              type: Type.OBJECT,
              properties: {
                songId: { type: Type.STRING, description: 'The UUID from the repertoire, or omit/null if suggesting an external song not in the list.', nullable: true },
                title: { type: Type.STRING, description: 'Title of the song' },
                reason: { type: Type.STRING, description: 'Why this song is placed here in the setlist.' },
                suggestedOrder: { type: Type.INTEGER }
              },
              required: ['title', 'reason', 'suggestedOrder']
            }
          }
        },
        required: ['setlistTitle', 'explanation', 'songs']
      };

      const response = await ai.models.generateContent({
        model: 'gemini-3.5-flash-lite',
        contents: prompt,
        config: {
          responseMimeType: 'application/json',
          // Note: responseSchema is supported natively in gemini-3.5-flash-lite
          responseSchema: responseSchema as any
        }
      });

      if (!response.text) {
        throw new Error('No text generated by Gemini');
      }

      const result = JSON.parse(response.text);
      res.json(result);

    } catch (error) {
      if (error instanceof z.ZodError) {
        return res.status(400).json({ error: 'Validation failed', details: error.issues });
      }
      console.error('AI Error:', error);
      res.status(500).json({ error: 'Failed to curate setlist from AI', details: error.message || 'Unknown error' });
    }
  }
}

export const aiController = new AiController();
